version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - '3000:3000'
    links:
      - mongo
    tty: true
    stdin_open: true

  mongo:
    image: mongo:4.2.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db  

volumes:
  mongodata:

